# Generated by Django 2.0 on 2019-03-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_apply', '0004_training_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField(default=False, verbose_name='Result')),
                ('report', models.CharField(max_length=300, verbose_name='Report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_report', to='job_apply.User')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_in_reports', to='job_apply.Vacancy')),
            ],
        ),
    ]
