# Generated by Django 2.0 on 2019-03-12 10:03

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_experience_position', models.CharField(max_length=300, verbose_name='Work Experience Position')),
                ('work_experience_employer', models.CharField(max_length=300, verbose_name='Work Experience Employer')),
                ('work_experience_location', models.CharField(max_length=300, verbose_name='Work Experience Location')),
                ('work_experience_starts', models.DateTimeField(verbose_name='End Data')),
                ('work_experience_ends', models.DateTimeField(verbose_name='End Data')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_institution', models.CharField(max_length=300, verbose_name='Training Institution')),
                ('training_degree', models.CharField(max_length=300, verbose_name='Training Degree')),
                ('training_major', models.CharField(max_length=300, verbose_name='Training Major')),
                ('training_starts', models.DateTimeField(verbose_name='Start Date')),
                ('training_ends', models.DateTimeField(verbose_name='End Data')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=300, verbose_name='Last Name')),
                ('email', models.CharField(max_length=300, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True)),
                ('avatar_url', models.CharField(max_length=300, verbose_name='Avatar URL')),
                ('cv_path', models.CharField(max_length=300, verbose_name='Cv_Path')),
                ('message', models.TextField(max_length=300, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='Link')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Training_User', to='job_apply.User'),
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience_User', to='job_apply.User'),
        ),
    ]
