# Generated by Django 2.0 on 2019-03-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_apply', '0002_auto_20190312_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
